"""
Maps questions to Microsoft Learn documentation URLs based on content analysis.
"""

import re
from typing import Optional


# Keyword → MS Learn URL patterns for AZ-900
AZ900_DOC_MAP = {
    # Cloud concepts
    "cloud models": "https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/fundamental-concepts",
    "public cloud": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "private cloud": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "hybrid cloud": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "iaas": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "paas": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "saas": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "infrastructure as a service": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "platform as a service": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "software as a service": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
    "shared responsibility": "https://learn.microsoft.com/en-us/azure/security/fundamentals/shared-responsibility",
    "capital expenditure": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "capex": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "opex": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    "consumption-based": "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
    # Infrastructure & regions
    "azure region": "https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview",
    "availability zone": "https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview",
    "availability set": "https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview",
    "fault domain": "https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview",
    "update domain": "https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview",
    "region pair": "https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure",
    "geographies": "https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview",
    "data residency": "https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview",
    "edge zone": "https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview",
    # Resource management
    "azure resource manager": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/overview",
    "resource group": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal",
    "resource lock": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources",
    "arm template": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/overview",
    "bicep": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview",
    "subscription": "https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription",
    "management group": "https://learn.microsoft.com/en-us/azure/governance/management-groups/overview",
    "azure blueprint": "https://learn.microsoft.com/en-us/azure/governance/blueprints/overview",
    "tag": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources",
    # Identity & access
    "azure active directory": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "azure ad": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "entra id": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "rbac": "https://learn.microsoft.com/en-us/azure/role-based-access-control/overview",
    "role-based access control": "https://learn.microsoft.com/en-us/azure/role-based-access-control/overview",
    "multi-factor authentication": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-howitworks",
    "mfa": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-howitworks",
    "conditional access": "https://learn.microsoft.com/en-us/entra/identity/conditional-access/overview",
    "single sign-on": "https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/what-is-single-sign-on",
    "sso": "https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/what-is-single-sign-on",
    "privileged identity": "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure",
    "zero trust": "https://learn.microsoft.com/en-us/azure/security/fundamentals/zero-trust",
    "defense in depth": "https://learn.microsoft.com/en-us/training/modules/describe-azure-identity-access-security/",
    # Governance & policy
    "azure policy": "https://learn.microsoft.com/en-us/azure/governance/policy/overview",
    "initiative": "https://learn.microsoft.com/en-us/azure/governance/policy/overview",
    "compliance": "https://learn.microsoft.com/en-us/azure/governance/policy/overview",
    # Compute
    "virtual machine": "https://learn.microsoft.com/en-us/azure/virtual-machines/overview",
    "azure virtual machine": "https://learn.microsoft.com/en-us/azure/virtual-machines/overview",
    "virtual machines": "https://learn.microsoft.com/en-us/azure/virtual-machines/overview",
    "vm scale set": "https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview",
    "scale set": "https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview",
    "app service": "https://learn.microsoft.com/en-us/azure/app-service/overview",
    "azure web app": "https://learn.microsoft.com/en-us/azure/app-service/overview",
    "web app": "https://learn.microsoft.com/en-us/azure/app-service/overview",
    "azure functions": "https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview",
    "function app": "https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview",
    "serverless": "https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview",
    "logic app": "https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-overview",
    "azure kubernetes": "https://learn.microsoft.com/en-us/azure/aks/intro-kubernetes",
    "aks": "https://learn.microsoft.com/en-us/azure/aks/intro-kubernetes",
    "kubernetes": "https://learn.microsoft.com/en-us/azure/aks/intro-kubernetes",
    "azure container": "https://learn.microsoft.com/en-us/azure/container-instances/container-instances-overview",
    "container instance": "https://learn.microsoft.com/en-us/azure/container-instances/container-instances-overview",
    "container registry": "https://learn.microsoft.com/en-us/azure/container-registry/container-registry-intro",
    "azure batch": "https://learn.microsoft.com/en-us/azure/batch/batch-technical-overview",
    "azure devtest": "https://learn.microsoft.com/en-us/azure/devtest-labs/devtest-lab-overview",
    # Storage
    "azure storage": "https://learn.microsoft.com/en-us/azure/storage/common/storage-introduction",
    "blob storage": "https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction",
    "blob": "https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction",
    "file share": "https://learn.microsoft.com/en-us/azure/storage/files/storage-files-introduction",
    "azure files": "https://learn.microsoft.com/en-us/azure/storage/files/storage-files-introduction",
    "queue storage": "https://learn.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction",
    "table storage": "https://learn.microsoft.com/en-us/azure/storage/tables/table-storage-overview",
    "disk storage": "https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview",
    "managed disk": "https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview",
    "storage redundancy": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "locally redundant": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "geo-redundant": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "zone-redundant": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "lrs": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "grs": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "zrs": "https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy",
    "storage tier": "https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview",
    "hot tier": "https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview",
    "cool tier": "https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview",
    "archive tier": "https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview",
    # Databases
    "azure sql": "https://learn.microsoft.com/en-us/azure/azure-sql/database/sql-database-paas-overview",
    "sql database": "https://learn.microsoft.com/en-us/azure/azure-sql/database/sql-database-paas-overview",
    "cosmos db": "https://learn.microsoft.com/en-us/azure/cosmos-db/introduction",
    "azure database for mysql": "https://learn.microsoft.com/en-us/azure/mysql/overview",
    "azure database for postgresql": "https://learn.microsoft.com/en-us/azure/postgresql/overview",
    "sql managed instance": "https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/sql-managed-instance-paas-overview",
    "synapse": "https://learn.microsoft.com/en-us/azure/synapse-analytics/overview-what-is",
    # Networking
    "virtual network": "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview",
    "vnet": "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview",
    "network security group": "https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview",
    "nsg": "https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview",
    "azure firewall": "https://learn.microsoft.com/en-us/azure/firewall/overview",
    "vpn gateway": "https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways",
    "expressroute": "https://learn.microsoft.com/en-us/azure/expressroute/expressroute-introduction",
    "express route": "https://learn.microsoft.com/en-us/azure/expressroute/expressroute-introduction",
    "peering": "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview",
    "vnet peering": "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview",
    "load balancer": "https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview",
    "application gateway": "https://learn.microsoft.com/en-us/azure/application-gateway/overview",
    "azure front door": "https://learn.microsoft.com/en-us/azure/frontdoor/front-door-overview",
    "traffic manager": "https://learn.microsoft.com/en-us/azure/traffic-manager/traffic-manager-overview",
    "azure cdn": "https://learn.microsoft.com/en-us/azure/cdn/cdn-overview",
    "azure dns": "https://learn.microsoft.com/en-us/azure/dns/dns-overview",
    "private endpoint": "https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview",
    "private link": "https://learn.microsoft.com/en-us/azure/private-link/private-link-overview",
    "ddos": "https://learn.microsoft.com/en-us/azure/ddos-protection/ddos-protection-overview",
    "azure bastion": "https://learn.microsoft.com/en-us/azure/bastion/bastion-overview",
    # Security & monitoring
    "azure monitor": "https://learn.microsoft.com/en-us/azure/azure-monitor/overview",
    "log analytics": "https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-overview",
    "application insights": "https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview",
    "azure sentinel": "https://learn.microsoft.com/en-us/azure/sentinel/overview",
    "microsoft sentinel": "https://learn.microsoft.com/en-us/azure/sentinel/overview",
    "azure security center": "https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction",
    "defender for cloud": "https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction",
    "microsoft defender for cloud": "https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction",
    "key vault": "https://learn.microsoft.com/en-us/azure/key-vault/general/overview",
    "azure key vault": "https://learn.microsoft.com/en-us/azure/key-vault/general/overview",
    "service health": "https://learn.microsoft.com/en-us/azure/service-health/overview",
    "azure service health": "https://learn.microsoft.com/en-us/azure/service-health/overview",
    "azure advisor": "https://learn.microsoft.com/en-us/azure/advisor/advisor-overview",
    "advisor": "https://learn.microsoft.com/en-us/azure/advisor/advisor-overview",
    "azure trust center": "https://learn.microsoft.com/en-us/azure/security/fundamentals/trust-center",
    "microsoft privacy": "https://learn.microsoft.com/en-us/azure/security/fundamentals/privacy-statement",
    "microsoft purview": "https://learn.microsoft.com/en-us/purview/purview",
    # Cost & SLA
    "azure cost management": "https://learn.microsoft.com/en-us/azure/cost-management-billing/cost-management-billing-overview",
    "total cost of ownership": "https://learn.microsoft.com/en-us/azure/cost-management-billing/cost-management-billing-overview",
    "tco": "https://learn.microsoft.com/en-us/azure/cost-management-billing/cost-management-billing-overview",
    "pricing calculator": "https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/pricing-calculator",
    "spending limit": "https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/spending-limit",
    "budget": "https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-acm-create-budgets",
    "sla": "https://learn.microsoft.com/en-us/azure/reliability/overview",
    "service level agreement": "https://learn.microsoft.com/en-us/azure/reliability/overview",
    "uptime": "https://learn.microsoft.com/en-us/azure/reliability/overview",
    "support plan": "https://learn.microsoft.com/en-us/azure/developer/intro/azure-developer-support",
    "support request": "https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request",
    # Messaging & integration
    "event hub": "https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-about",
    "event grid": "https://learn.microsoft.com/en-us/azure/event-grid/overview",
    "service bus": "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview",
    "azure queue": "https://learn.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction",
    "notification hub": "https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview",
    # DevOps & migration
    "azure devops": "https://learn.microsoft.com/en-us/azure/devops/user-guide/what-is-azure-devops",
    "github actions": "https://learn.microsoft.com/en-us/azure/developer/github/github-actions",
    "azure migrate": "https://learn.microsoft.com/en-us/azure/migrate/migrate-services-overview",
    "azure site recovery": "https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview",
    "azure backup": "https://learn.microsoft.com/en-us/azure/backup/backup-overview",
    "disaster recovery": "https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview",
}


def find_documentation_links(question_text: str, cert_code: str) -> list[dict]:
    """
    Find relevant documentation links for a question based on keyword matching.
    Returns a list of {url, title} dicts.
    """
    text_lower = question_text.lower()
    found_links = {}

    doc_map = _get_doc_map(cert_code)

    for keyword, url in doc_map.items():
        if keyword in text_lower and url not in found_links:
            title = _url_to_title(url)
            found_links[url] = {"url": url, "title": title}
            if len(found_links) >= 3:
                break

    return list(found_links.values())


MD102_DOC_MAP = {
    "autopilot": "https://learn.microsoft.com/en-us/autopilot/windows-autopilot",
    "windows autopilot": "https://learn.microsoft.com/en-us/autopilot/windows-autopilot",
    "autopilot deployment profile": "https://learn.microsoft.com/en-us/autopilot/profiles",
    "autopilot reset": "https://learn.microsoft.com/en-us/autopilot/windows-autopilot-reset",
    "hybrid azure ad join": "https://learn.microsoft.com/en-us/entra/identity/devices/hybrid-join-plan",
    "hybrid joined": "https://learn.microsoft.com/en-us/entra/identity/devices/hybrid-join-plan",
    "azure ad join": "https://learn.microsoft.com/en-us/entra/identity/devices/concept-directory-joined",
    "azure ad registered": "https://learn.microsoft.com/en-us/entra/identity/devices/concept-device-registration",
    "microsoft intune": "https://learn.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune",
    "intune": "https://learn.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune",
    "mdm enrollment": "https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-methods",
    "device enrollment": "https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-methods",
    "compliance policy": "https://learn.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started",
    "configuration profile": "https://learn.microsoft.com/en-us/mem/intune/configuration/device-profiles",
    "endpoint security": "https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security",
    "security baseline": "https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines",
    "bitlocker": "https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/",
    "windows update for business": "https://learn.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb",
    "update ring": "https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-update-rings",
    "app protection policy": "https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policies",
    "mam": "https://learn.microsoft.com/en-us/mem/intune/apps/app-management",
    "app deployment": "https://learn.microsoft.com/en-us/mem/intune/apps/apps-add",
    "win32 app": "https://learn.microsoft.com/en-us/mem/intune/apps/apps-win32-app-management",
    "microsoft store": "https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-windows",
    "enterprise state roaming": "https://learn.microsoft.com/en-us/entra/identity/devices/enterprise-state-roaming-enable",
    "conditional access": "https://learn.microsoft.com/en-us/entra/identity/conditional-access/overview",
    "co-management": "https://learn.microsoft.com/en-us/mem/configmgr/comanage/overview",
    "configuration manager": "https://learn.microsoft.com/en-us/mem/configmgr/core/understand/introduction",
    "windows defender": "https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows",
    "microsoft defender for endpoint": "https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint",
    "attack surface reduction": "https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction",
    "controlled folder access": "https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders",
    "windows hello": "https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/",
    "kiosk": "https://learn.microsoft.com/en-us/windows/configuration/assigned-access/overview",
    "assigned access": "https://learn.microsoft.com/en-us/windows/configuration/assigned-access/overview",
    "subscription activation": "https://learn.microsoft.com/en-us/windows/deployment/windows-subscription-activation",
    "delivery optimization": "https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization",
    "remote wipe": "https://learn.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe",
    "remote lock": "https://learn.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock",
    "autopilot self-deploying": "https://learn.microsoft.com/en-us/autopilot/self-deploying",
    "user-driven mode": "https://learn.microsoft.com/en-us/autopilot/user-driven",
    "enrollment status page": "https://learn.microsoft.com/en-us/autopilot/enrollment-status",
    "esp": "https://learn.microsoft.com/en-us/autopilot/enrollment-status",
    "microsoft endpoint manager": "https://learn.microsoft.com/en-us/mem/",
    "powershell script": "https://learn.microsoft.com/en-us/mem/intune/apps/intune-management-extension",
    "scope tag": "https://learn.microsoft.com/en-us/mem/intune/fundamentals/scope-tags",
    "group policy": "https://learn.microsoft.com/en-us/windows/client-management/group-policies-for-enterprise-and-education-editions",
    "administrative template": "https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-windows",
    "admx": "https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-windows",
    "feature update": "https://learn.microsoft.com/en-us/mem/intune/protect/windows-10-feature-updates",
    "quality update": "https://learn.microsoft.com/en-us/mem/intune/protect/windows-update-settings",
    "microsoft 365 apps": "https://learn.microsoft.com/en-us/mem/intune/apps/apps-add-office365",
    "office 365": "https://learn.microsoft.com/en-us/mem/intune/apps/apps-add-office365",
    "volume license": "https://learn.microsoft.com/en-us/windows/deployment/volume-activation/volume-activation-windows",
}


MS102_DOC_MAP = {
    "microsoft 365 tenant": "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/microsoft-365-admin-center-preview",
    "tenant": "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/microsoft-365-admin-center-preview",
    "microsoft 365 admin center": "https://learn.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview",
    "exchange online": "https://learn.microsoft.com/en-us/exchange/exchange-online",
    "sharepoint online": "https://learn.microsoft.com/en-us/sharepoint/sharepoint-online",
    "microsoft teams": "https://learn.microsoft.com/en-us/microsoftteams/teams-overview",
    "onedrive for business": "https://learn.microsoft.com/en-us/onedrive/onedrive",
    "microsoft 365 groups": "https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups",
    "conditional access": "https://learn.microsoft.com/en-us/entra/identity/conditional-access/overview",
    "multi-factor authentication": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-howitworks",
    "mfa": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-howitworks",
    "azure ad": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "microsoft entra id": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "entra id": "https://learn.microsoft.com/en-us/entra/fundamentals/what-is-entra-id",
    "privileged identity management": "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure",
    "pim": "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure",
    "microsoft purview": "https://learn.microsoft.com/en-us/purview/purview",
    "data loss prevention": "https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp",
    "dlp": "https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp",
    "sensitivity label": "https://learn.microsoft.com/en-us/purview/sensitivity-labels",
    "retention policy": "https://learn.microsoft.com/en-us/purview/retention-policies",
    "retention label": "https://learn.microsoft.com/en-us/purview/retention-labels",
    "ediscovery": "https://learn.microsoft.com/en-us/purview/ediscovery",
    "content search": "https://learn.microsoft.com/en-us/purview/content-search-overview",
    "audit log": "https://learn.microsoft.com/en-us/purview/audit-solutions-overview",
    "microsoft defender for office 365": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-about",
    "defender for office": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-about",
    "safe links": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about",
    "safe attachments": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments-about",
    "anti-spam": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection-about",
    "anti-malware": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection-about",
    "microsoft secure score": "https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score",
    "secure score": "https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score",
    "microsoft 365 defender": "https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender",
    "defender xdr": "https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender",
    "microsoft 365 apps": "https://learn.microsoft.com/en-us/deployoffice/overview-microsoft-365-apps",
    "office deployment tool": "https://learn.microsoft.com/en-us/deployoffice/overview-office-deployment-tool",
    "odt": "https://learn.microsoft.com/en-us/deployoffice/overview-office-deployment-tool",
    "microsoft 365 licensing": "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/set-up-dns-records-for-microsoft-365",
    "rbac": "https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles",
    "admin role": "https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles",
    "global administrator": "https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference",
    "domain": "https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-domain",
    "custom domain": "https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-domain",
    "hybrid identity": "https://learn.microsoft.com/en-us/entra/identity/hybrid/whatis-hybrid-identity",
    "azure ad connect": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect",
    "entra connect": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect",
    "password hash sync": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-phs",
    "pass-through authentication": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-pta",
    "federation": "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-fed",
    "sspr": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-howitworks",
    "self-service password reset": "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-howitworks",
    "access review": "https://learn.microsoft.com/en-us/entra/id-governance/access-reviews-overview",
    "entitlement management": "https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-overview",
    "compliance center": "https://learn.microsoft.com/en-us/purview/purview",
    "communication compliance": "https://learn.microsoft.com/en-us/purview/communication-compliance",
    "information barrier": "https://learn.microsoft.com/en-us/purview/information-barriers",
    "insider risk": "https://learn.microsoft.com/en-us/purview/insider-risk-management",
    "customer lockbox": "https://learn.microsoft.com/en-us/purview/customer-lockbox-requests",
    "microsoft 365 message encryption": "https://learn.microsoft.com/en-us/purview/email-encryption",
    "advanced message encryption": "https://learn.microsoft.com/en-us/purview/advanced-message-encryption",
    "mail flow rule": "https://learn.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules",
    "transport rule": "https://learn.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules",
    "mailbox": "https://learn.microsoft.com/en-us/exchange/recipients/user-mailboxes/user-mailboxes",
    "shared mailbox": "https://learn.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox",
    "distribution group": "https://learn.microsoft.com/en-us/exchange/recipients/distribution-groups",
    "dynamic distribution group": "https://learn.microsoft.com/en-us/exchange/recipients/dynamic-distribution-groups/dynamic-distribution-groups",
    "microsoft 365 backup": "https://learn.microsoft.com/en-us/microsoft-365/backup/backup-overview",
    "service health": "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/health-dashboard-overview",
}


PL300_DOC_MAP = {
    # Power Query / data prep
    "power query": "https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query",
    "power query editor": "https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query",
    "replace values": "https://learn.microsoft.com/en-us/power-query/replace-values",
    "replace errors": "https://learn.microsoft.com/en-us/power-query/dealing-with-errors",
    "pivot column": "https://learn.microsoft.com/en-us/power-query/pivot-columns",
    "unpivot": "https://learn.microsoft.com/en-us/power-query/unpivot-column",
    "merge queries": "https://learn.microsoft.com/en-us/power-query/merge-queries-overview",
    "left outer join": "https://learn.microsoft.com/en-us/power-query/merge-queries-left-outer",
    "append queries": "https://learn.microsoft.com/en-us/power-query/append-queries",
    "group by": "https://learn.microsoft.com/en-us/power-query/group-by",
    "data types": "https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-types",
    "query folding": "https://learn.microsoft.com/en-us/power-query/power-query-folding",
    # Star schema / data modeling
    "star schema": "https://learn.microsoft.com/en-us/power-bi/guidance/star-schema",
    "fact table": "https://learn.microsoft.com/en-us/power-bi/guidance/star-schema",
    "dimension table": "https://learn.microsoft.com/en-us/power-bi/guidance/star-schema",
    "semantic model": "https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-understand",
    "data model": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand",
    # Relationships
    "relationship": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand",
    "cardinality": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand",
    "one-to-many": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand",
    "many-to-many": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-many-to-many-relationships",
    "role-playing dimension": "https://learn.microsoft.com/en-us/power-bi/guidance/relationships-one-to-one",
    "mark as date table": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-date-tables",
    "date table": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-date-tables",
    # DAX
    "dax": "https://learn.microsoft.com/en-us/dax/dax-overview",
    "calculated column": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-calculated-columns",
    "calculated table": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-calculated-tables",
    "measure": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-measures",
    "calculate function": "https://learn.microsoft.com/en-us/dax/calculate-function-dax",
    "sameperiodlastyear": "https://learn.microsoft.com/en-us/dax/sameperiodlastyear-function-dax",
    "time intelligence": "https://learn.microsoft.com/en-us/dax/time-intelligence-functions-dax",
    "removefilters": "https://learn.microsoft.com/en-us/dax/removefilters-function-dax",
    "filter context": "https://learn.microsoft.com/en-us/power-bi/guidance/dax-understand-context",
    "row context": "https://learn.microsoft.com/en-us/power-bi/guidance/dax-understand-context",
    "median": "https://learn.microsoft.com/en-us/dax/median-function-dax",
    "lastnonblank": "https://learn.microsoft.com/en-us/dax/lastnonblank-function-dax",
    "firstnonblank": "https://learn.microsoft.com/en-us/dax/firstnonblank-function-dax",
    "rankx": "https://learn.microsoft.com/en-us/dax/rankx-function-dax",
    # Model performance
    "performance analyzer": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-performance-analyzer",
    "aggregation": "https://learn.microsoft.com/en-us/power-bi/transform-model/aggregations-advanced",
    "import mode": "https://learn.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand",
    "directquery": "https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about",
    "composite model": "https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models",
    # Visuals
    "visualization": "https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a",
    "scatter chart": "https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter",
    "matrix visual": "https://learn.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual",
    "anomaly detection": "https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-anomaly-detection",
    "clustering": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-visuals",
    # Q&A
    "q&a": "https://learn.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a",
    "synonym": "https://learn.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-intro",
    "natural language": "https://learn.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-intro",
    # Report design
    "bookmark": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-bookmarks",
    "selection pane": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-bookmarks",
    "tooltip": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips",
    "report tooltip": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips",
    "canvas background": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes",
    "wallpaper": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes",
    "edit interactions": "https://learn.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions",
    "visual interaction": "https://learn.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions",
    "drill down": "https://learn.microsoft.com/en-us/power-bi/consumer/end-user-drill",
    "drill through": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough",
    "layer order": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-creating-reports",
    "conditional formatting": "https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-format-visual-titles",
    "slicer": "https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers",
    # Paginated reports
    "paginated report": "https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi",
    "report builder": "https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi",
    # Service / deployment
    "power bi service": "https://learn.microsoft.com/en-us/power-bi/fundamentals/power-bi-service-overview",
    "workspace": "https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-the-new-workspaces",
    "power bi app": "https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps",
    "scheduled refresh": "https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-scheduled-refresh",
    "data refresh": "https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data",
    "gateway": "https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem",
    "on-premises data gateway": "https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem",
    "row-level security": "https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls",
    "rls": "https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls",
    "build permission": "https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions",
    "analyze in excel": "https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel",
    "shared capacity": "https://learn.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type",
    "premium capacity": "https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is",
    "power bi desktop": "https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop",
    "deployment pipeline": "https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-overview",
    "endorsement": "https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-endorse-content",
}


def _get_doc_map(cert_code: str) -> dict:
    """Get the keyword→URL map for a specific cert."""
    maps = {
        "AZ-900": AZ900_DOC_MAP,
        "AZ-104": AZ900_DOC_MAP,
        "MD-102": MD102_DOC_MAP,
        "MS-102": MS102_DOC_MAP,
        "PL-300": PL300_DOC_MAP,
    }
    return maps.get(cert_code, AZ900_DOC_MAP)


def _url_to_title(url: str) -> str:
    """Convert a URL to a human-readable title."""
    path = url.split("learn.microsoft.com/en-us/")[-1].rstrip("/")
    parts = path.split("/")
    # Take last 2 meaningful parts
    title = " › ".join(
        part.replace("-", " ").title()
        for part in parts[-2:]
        if part and part != "overview"
    )
    return title or "Microsoft Learn Documentation"
